package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * AlumnoHasGrupo generated by hbm2java
 */
public class AlumnoHasGrupo  implements java.io.Serializable {


     private AlumnoHasGrupoId id;

    public AlumnoHasGrupo() {
    }

    public AlumnoHasGrupo(AlumnoHasGrupoId id) {
       this.id = id;
    }
   
    public AlumnoHasGrupoId getId() {
        return this.id;
    }
    
    public void setId(AlumnoHasGrupoId id) {
        this.id = id;
    }




}


