package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * AlumnoHasGrupoId generated by hbm2java
 */
public class AlumnoHasGrupoId  implements java.io.Serializable {


     private int alumnoMatricula;
     private String grupoGrupo;
     private String grupoTrimestreLectivo;

    public AlumnoHasGrupoId() {
    }

    public AlumnoHasGrupoId(int alumnoMatricula, String grupoGrupo, String grupoTrimestreLectivo) {
       this.alumnoMatricula = alumnoMatricula;
       this.grupoGrupo = grupoGrupo;
       this.grupoTrimestreLectivo = grupoTrimestreLectivo;
    }
   
    public int getAlumnoMatricula() {
        return this.alumnoMatricula;
    }
    
    public void setAlumnoMatricula(int alumnoMatricula) {
        this.alumnoMatricula = alumnoMatricula;
    }
    public String getGrupoGrupo() {
        return this.grupoGrupo;
    }
    
    public void setGrupoGrupo(String grupoGrupo) {
        this.grupoGrupo = grupoGrupo;
    }
    public String getGrupoTrimestreLectivo() {
        return this.grupoTrimestreLectivo;
    }
    
    public void setGrupoTrimestreLectivo(String grupoTrimestreLectivo) {
        this.grupoTrimestreLectivo = grupoTrimestreLectivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoHasGrupoId) ) return false;
		 AlumnoHasGrupoId castOther = ( AlumnoHasGrupoId ) other; 
         
		 return (this.getAlumnoMatricula()==castOther.getAlumnoMatricula())
 && ( (this.getGrupoGrupo()==castOther.getGrupoGrupo()) || ( this.getGrupoGrupo()!=null && castOther.getGrupoGrupo()!=null && this.getGrupoGrupo().equals(castOther.getGrupoGrupo()) ) )
 && ( (this.getGrupoTrimestreLectivo()==castOther.getGrupoTrimestreLectivo()) || ( this.getGrupoTrimestreLectivo()!=null && castOther.getGrupoTrimestreLectivo()!=null && this.getGrupoTrimestreLectivo().equals(castOther.getGrupoTrimestreLectivo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlumnoMatricula();
         result = 37 * result + ( getGrupoGrupo() == null ? 0 : this.getGrupoGrupo().hashCode() );
         result = 37 * result + ( getGrupoTrimestreLectivo() == null ? 0 : this.getGrupoTrimestreLectivo().hashCode() );
         return result;
   }   


}


