package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FaseAlumnoTarea generated by hbm2java
 */
public class FaseAlumnoTarea  implements java.io.Serializable {


     private FaseAlumnoTareaId id;
     private Date tiempoPlaneado;
     private Date tiempoReal;
     private Integer defectosPlaneados;
     private Integer defectosReal;
     private Integer defectosEliminadosPlaneados;
     private Integer defectosEliminadosReal;
     private String alumnoHasGrupoGrupoGrupo;
     private String alumnoHasGrupoGrupoTrimestreLectivo;

    public FaseAlumnoTarea() {
    }

	
    public FaseAlumnoTarea(FaseAlumnoTareaId id, String alumnoHasGrupoGrupoGrupo, String alumnoHasGrupoGrupoTrimestreLectivo) {
        this.id = id;
        this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
        this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }
    public FaseAlumnoTarea(FaseAlumnoTareaId id, Date tiempoPlaneado, Date tiempoReal, Integer defectosPlaneados, Integer defectosReal, Integer defectosEliminadosPlaneados, Integer defectosEliminadosReal, String alumnoHasGrupoGrupoGrupo, String alumnoHasGrupoGrupoTrimestreLectivo) {
       this.id = id;
       this.tiempoPlaneado = tiempoPlaneado;
       this.tiempoReal = tiempoReal;
       this.defectosPlaneados = defectosPlaneados;
       this.defectosReal = defectosReal;
       this.defectosEliminadosPlaneados = defectosEliminadosPlaneados;
       this.defectosEliminadosReal = defectosEliminadosReal;
       this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
       this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }
   
    public FaseAlumnoTareaId getId() {
        return this.id;
    }
    
    public void setId(FaseAlumnoTareaId id) {
        this.id = id;
    }
    public Date getTiempoPlaneado() {
        return this.tiempoPlaneado;
    }
    
    public void setTiempoPlaneado(Date tiempoPlaneado) {
        this.tiempoPlaneado = tiempoPlaneado;
    }
    public Date getTiempoReal() {
        return this.tiempoReal;
    }
    
    public void setTiempoReal(Date tiempoReal) {
        this.tiempoReal = tiempoReal;
    }
    public Integer getDefectosPlaneados() {
        return this.defectosPlaneados;
    }
    
    public void setDefectosPlaneados(Integer defectosPlaneados) {
        this.defectosPlaneados = defectosPlaneados;
    }
    public Integer getDefectosReal() {
        return this.defectosReal;
    }
    
    public void setDefectosReal(Integer defectosReal) {
        this.defectosReal = defectosReal;
    }
    public Integer getDefectosEliminadosPlaneados() {
        return this.defectosEliminadosPlaneados;
    }
    
    public void setDefectosEliminadosPlaneados(Integer defectosEliminadosPlaneados) {
        this.defectosEliminadosPlaneados = defectosEliminadosPlaneados;
    }
    public Integer getDefectosEliminadosReal() {
        return this.defectosEliminadosReal;
    }
    
    public void setDefectosEliminadosReal(Integer defectosEliminadosReal) {
        this.defectosEliminadosReal = defectosEliminadosReal;
    }
    public String getAlumnoHasGrupoGrupoGrupo() {
        return this.alumnoHasGrupoGrupoGrupo;
    }
    
    public void setAlumnoHasGrupoGrupoGrupo(String alumnoHasGrupoGrupoGrupo) {
        this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
    }
    public String getAlumnoHasGrupoGrupoTrimestreLectivo() {
        return this.alumnoHasGrupoGrupoTrimestreLectivo;
    }
    
    public void setAlumnoHasGrupoGrupoTrimestreLectivo(String alumnoHasGrupoGrupoTrimestreLectivo) {
        this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }




}


