package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private GrupoId id;
     private Integer numeroEmpleado;
     private Integer cupo;
     private Integer numeroInscritos;

    public Grupo() {
    }

	
    public Grupo(GrupoId id) {
        this.id = id;
    }
    public Grupo(GrupoId id, Integer numeroEmpleado, Integer cupo, Integer numeroInscritos) {
       this.id = id;
       this.numeroEmpleado = numeroEmpleado;
       this.cupo = cupo;
       this.numeroInscritos = numeroInscritos;
    }
   
    public GrupoId getId() {
        return this.id;
    }
    
    public void setId(GrupoId id) {
        this.id = id;
    }
    public Integer getNumeroEmpleado() {
        return this.numeroEmpleado;
    }
    
    public void setNumeroEmpleado(Integer numeroEmpleado) {
        this.numeroEmpleado = numeroEmpleado;
    }
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    public Integer getNumeroInscritos() {
        return this.numeroInscritos;
    }
    
    public void setNumeroInscritos(Integer numeroInscritos) {
        this.numeroInscritos = numeroInscritos;
    }




}


