package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * GrupoId generated by hbm2java
 */
public class GrupoId  implements java.io.Serializable {


     private String grupo;
     private String trimestreLectivo;

    public GrupoId() {
    }

    public GrupoId(String grupo, String trimestreLectivo) {
       this.grupo = grupo;
       this.trimestreLectivo = trimestreLectivo;
    }
   
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getTrimestreLectivo() {
        return this.trimestreLectivo;
    }
    
    public void setTrimestreLectivo(String trimestreLectivo) {
        this.trimestreLectivo = trimestreLectivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupoId) ) return false;
		 GrupoId castOther = ( GrupoId ) other; 
         
		 return ( (this.getGrupo()==castOther.getGrupo()) || ( this.getGrupo()!=null && castOther.getGrupo()!=null && this.getGrupo().equals(castOther.getGrupo()) ) )
 && ( (this.getTrimestreLectivo()==castOther.getTrimestreLectivo()) || ( this.getTrimestreLectivo()!=null && castOther.getTrimestreLectivo()!=null && this.getTrimestreLectivo().equals(castOther.getTrimestreLectivo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrupo() == null ? 0 : this.getGrupo().hashCode() );
         result = 37 * result + ( getTrimestreLectivo() == null ? 0 : this.getTrimestreLectivo().hashCode() );
         return result;
   }   


}


