package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int numeroEmpleado;
     private String nombre;
     private String cotrasena;

    public Profesor() {
    }

	
    public Profesor(int numeroEmpleado, String nombre) {
        this.numeroEmpleado = numeroEmpleado;
        this.nombre = nombre;
    }
    public Profesor(int numeroEmpleado, String nombre, String cotrasena) {
       this.numeroEmpleado = numeroEmpleado;
       this.nombre = nombre;
       this.cotrasena = cotrasena;
    }
   
    public int getNumeroEmpleado() {
        return this.numeroEmpleado;
    }
    
    public void setNumeroEmpleado(int numeroEmpleado) {
        this.numeroEmpleado = numeroEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCotrasena() {
        return this.cotrasena;
    }
    
    public void setCotrasena(String cotrasena) {
        this.cotrasena = cotrasena;
    }




}


