package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * TareaAlumno generated by hbm2java
 */
public class TareaAlumno  implements java.io.Serializable {


     private TareaAlumnoId id;
     private Integer basePlaneadas;
     private Integer baseReales;
     private Integer reutilizadoPlaneado;
     private Integer reutilizadoReal;
     private Integer eliminadoPlaneado;
     private Integer eliminadoReal;
     private Integer modificadoPlaneado;
     private Integer modificadoReal;
     private Integer agregadasModificadasPlaneadas;
     private Integer totalPlaneado;
     private Integer totalReal;
     private Integer nuevoReutilizadoPlaneado;
     private String metodoEstimacionTamano;
     private String metodoEstimacionTiempo;
     private Double lpitamano;
     private Double lpitiempo;
     private Double upitamano;
     private Double upitiempo;
     private String alumnoHasGrupoGrupoGrupo;
     private String alumnoHasGrupoGrupoTrimestreLectivo;

    public TareaAlumno() {
    }

	
    public TareaAlumno(TareaAlumnoId id, String alumnoHasGrupoGrupoGrupo, String alumnoHasGrupoGrupoTrimestreLectivo) {
        this.id = id;
        this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
        this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }
    public TareaAlumno(TareaAlumnoId id, Integer basePlaneadas, Integer baseReales, Integer reutilizadoPlaneado, Integer reutilizadoReal, Integer eliminadoPlaneado, Integer eliminadoReal, Integer modificadoPlaneado, Integer modificadoReal, Integer agregadasModificadasPlaneadas, Integer totalPlaneado, Integer totalReal, Integer nuevoReutilizadoPlaneado, String metodoEstimacionTamano, String metodoEstimacionTiempo, Double lpitamano, Double lpitiempo, Double upitamano, Double upitiempo, String alumnoHasGrupoGrupoGrupo, String alumnoHasGrupoGrupoTrimestreLectivo) {
       this.id = id;
       this.basePlaneadas = basePlaneadas;
       this.baseReales = baseReales;
       this.reutilizadoPlaneado = reutilizadoPlaneado;
       this.reutilizadoReal = reutilizadoReal;
       this.eliminadoPlaneado = eliminadoPlaneado;
       this.eliminadoReal = eliminadoReal;
       this.modificadoPlaneado = modificadoPlaneado;
       this.modificadoReal = modificadoReal;
       this.agregadasModificadasPlaneadas = agregadasModificadasPlaneadas;
       this.totalPlaneado = totalPlaneado;
       this.totalReal = totalReal;
       this.nuevoReutilizadoPlaneado = nuevoReutilizadoPlaneado;
       this.metodoEstimacionTamano = metodoEstimacionTamano;
       this.metodoEstimacionTiempo = metodoEstimacionTiempo;
       this.lpitamano = lpitamano;
       this.lpitiempo = lpitiempo;
       this.upitamano = upitamano;
       this.upitiempo = upitiempo;
       this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
       this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }
   
    public TareaAlumnoId getId() {
        return this.id;
    }
    
    public void setId(TareaAlumnoId id) {
        this.id = id;
    }
    public Integer getBasePlaneadas() {
        return this.basePlaneadas;
    }
    
    public void setBasePlaneadas(Integer basePlaneadas) {
        this.basePlaneadas = basePlaneadas;
    }
    public Integer getBaseReales() {
        return this.baseReales;
    }
    
    public void setBaseReales(Integer baseReales) {
        this.baseReales = baseReales;
    }
    public Integer getReutilizadoPlaneado() {
        return this.reutilizadoPlaneado;
    }
    
    public void setReutilizadoPlaneado(Integer reutilizadoPlaneado) {
        this.reutilizadoPlaneado = reutilizadoPlaneado;
    }
    public Integer getReutilizadoReal() {
        return this.reutilizadoReal;
    }
    
    public void setReutilizadoReal(Integer reutilizadoReal) {
        this.reutilizadoReal = reutilizadoReal;
    }
    public Integer getEliminadoPlaneado() {
        return this.eliminadoPlaneado;
    }
    
    public void setEliminadoPlaneado(Integer eliminadoPlaneado) {
        this.eliminadoPlaneado = eliminadoPlaneado;
    }
    public Integer getEliminadoReal() {
        return this.eliminadoReal;
    }
    
    public void setEliminadoReal(Integer eliminadoReal) {
        this.eliminadoReal = eliminadoReal;
    }
    public Integer getModificadoPlaneado() {
        return this.modificadoPlaneado;
    }
    
    public void setModificadoPlaneado(Integer modificadoPlaneado) {
        this.modificadoPlaneado = modificadoPlaneado;
    }
    public Integer getModificadoReal() {
        return this.modificadoReal;
    }
    
    public void setModificadoReal(Integer modificadoReal) {
        this.modificadoReal = modificadoReal;
    }
    public Integer getAgregadasModificadasPlaneadas() {
        return this.agregadasModificadasPlaneadas;
    }
    
    public void setAgregadasModificadasPlaneadas(Integer agregadasModificadasPlaneadas) {
        this.agregadasModificadasPlaneadas = agregadasModificadasPlaneadas;
    }
    public Integer getTotalPlaneado() {
        return this.totalPlaneado;
    }
    
    public void setTotalPlaneado(Integer totalPlaneado) {
        this.totalPlaneado = totalPlaneado;
    }
    public Integer getTotalReal() {
        return this.totalReal;
    }
    
    public void setTotalReal(Integer totalReal) {
        this.totalReal = totalReal;
    }
    public Integer getNuevoReutilizadoPlaneado() {
        return this.nuevoReutilizadoPlaneado;
    }
    
    public void setNuevoReutilizadoPlaneado(Integer nuevoReutilizadoPlaneado) {
        this.nuevoReutilizadoPlaneado = nuevoReutilizadoPlaneado;
    }
    public String getMetodoEstimacionTamano() {
        return this.metodoEstimacionTamano;
    }
    
    public void setMetodoEstimacionTamano(String metodoEstimacionTamano) {
        this.metodoEstimacionTamano = metodoEstimacionTamano;
    }
    public String getMetodoEstimacionTiempo() {
        return this.metodoEstimacionTiempo;
    }
    
    public void setMetodoEstimacionTiempo(String metodoEstimacionTiempo) {
        this.metodoEstimacionTiempo = metodoEstimacionTiempo;
    }
    public Double getLpitamano() {
        return this.lpitamano;
    }
    
    public void setLpitamano(Double lpitamano) {
        this.lpitamano = lpitamano;
    }
    public Double getLpitiempo() {
        return this.lpitiempo;
    }
    
    public void setLpitiempo(Double lpitiempo) {
        this.lpitiempo = lpitiempo;
    }
    public Double getUpitamano() {
        return this.upitamano;
    }
    
    public void setUpitamano(Double upitamano) {
        this.upitamano = upitamano;
    }
    public Double getUpitiempo() {
        return this.upitiempo;
    }
    
    public void setUpitiempo(Double upitiempo) {
        this.upitiempo = upitiempo;
    }
    public String getAlumnoHasGrupoGrupoGrupo() {
        return this.alumnoHasGrupoGrupoGrupo;
    }
    
    public void setAlumnoHasGrupoGrupoGrupo(String alumnoHasGrupoGrupoGrupo) {
        this.alumnoHasGrupoGrupoGrupo = alumnoHasGrupoGrupoGrupo;
    }
    public String getAlumnoHasGrupoGrupoTrimestreLectivo() {
        return this.alumnoHasGrupoGrupoTrimestreLectivo;
    }
    
    public void setAlumnoHasGrupoGrupoTrimestreLectivo(String alumnoHasGrupoGrupoTrimestreLectivo) {
        this.alumnoHasGrupoGrupoTrimestreLectivo = alumnoHasGrupoGrupoTrimestreLectivo;
    }




}


