package Modelo;
// Generated 19/08/2015 04:41:40 PM by Hibernate Tools 4.3.1



/**
 * TareaAlumnoId generated by hbm2java
 */
public class TareaAlumnoId  implements java.io.Serializable {


     private int numeroTarea;
     private int alumnoHasGrupoAlumnoMatricula;

    public TareaAlumnoId() {
    }

    public TareaAlumnoId(int numeroTarea, int alumnoHasGrupoAlumnoMatricula) {
       this.numeroTarea = numeroTarea;
       this.alumnoHasGrupoAlumnoMatricula = alumnoHasGrupoAlumnoMatricula;
    }
   
    public int getNumeroTarea() {
        return this.numeroTarea;
    }
    
    public void setNumeroTarea(int numeroTarea) {
        this.numeroTarea = numeroTarea;
    }
    public int getAlumnoHasGrupoAlumnoMatricula() {
        return this.alumnoHasGrupoAlumnoMatricula;
    }
    
    public void setAlumnoHasGrupoAlumnoMatricula(int alumnoHasGrupoAlumnoMatricula) {
        this.alumnoHasGrupoAlumnoMatricula = alumnoHasGrupoAlumnoMatricula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TareaAlumnoId) ) return false;
		 TareaAlumnoId castOther = ( TareaAlumnoId ) other; 
         
		 return (this.getNumeroTarea()==castOther.getNumeroTarea())
 && (this.getAlumnoHasGrupoAlumnoMatricula()==castOther.getAlumnoHasGrupoAlumnoMatricula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumeroTarea();
         result = 37 * result + this.getAlumnoHasGrupoAlumnoMatricula();
         return result;
   }   


}


